### ISSUE TITLE
Update README with build/test/serve instructions

### ISSUE THREAD

**Issue by oscarcpozas** [OSWeekends/spoty-mix#2]

**Comment by jsdario** [comment]
Also a brief description of the project and a little bit of roadmap so the rest of us know how to help would be great

**Comment by jsdario** [comment]
Is still woud have been great to have a little more literature and some screenshots. I'l give it a look and try to PR.

**Comment by JoseAntpr** [comment]
You´re right... But yesterday was a crazy day.
